docs(website): added new package creation guide
glasskube/glasskube pull request #1011
Opened 2024-07-17 11:11 UTC by jakepage91

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-07-17 16:16 UTC, christophenne reviewed
Overall a nice guide :+1: It covers most parts – the only thing I would add are some additional references to docs here and there (see comments).

2024-07-17 16:17 UTC, christophenne reviewed
Overall a nice guide :+1: It covers most parts – the only thing I would add are some additional references to docs here and there (see comments).

2024-07-17 16:18 UTC, christophenne commented on website/guides/08_package-creation.mdx
> +### Step 5: Test your package integration
and vice versa, the contribution guidelines could link to this guide for more detailed instructions

2024-07-18 10:52 UTC, jakepage91 commented on website/guides/08_package-creation.mdx
> +Find the repo [here](https://medium.com/r/?url=https%3A%2F%2Fgithub.com%2Fglasskube%2Fpackages%2Ftree%2Fmain).
Oh yeah to help with markdown formatting I used a tool to generate the MDX from the post on Medium. Totally missed the links that are messed up.

2024-07-18 11:02 UTC, jakepage91 commented on website/guides/08_package-creation.mdx
> +-   **Root packages folder:** where all packages definition files can be found
Does this work? 
**Level 1**

-   **Folder per package**
-   **index.yaml** File which holds important information about each package (updated automatically during CI but manually during testing)

2024-07-18 11:22 UTC, jakepage91 commented on website/guides/08_package-creation.mdx
> +### Step 6: Access Glasskube Dashboard and install the package
How about this? 

> Please note that any changes made to your package repository will not be picked up automatically. To ensure all caches are cleared, either wait 5 minutes or restart both the operator and the UI. This is a known issue that will be addressed in a future version.

2024-07-18 16:18 UTC, pmig requested changes

2024-07-19 06:48 UTC, christophenne requested changes

2024-07-19 06:48 UTC, christophenne commented on website/guides/08_package-creation.mdx
> +> _In this guide we will learn how to add a Package by integrating the_ [_Argo Workflows_](https://medium.com/r/?url=https%3A%2F%2Fargoproj.github.io%2Fworkflows%2F) _controller._
Please replace the medium link here too.

2024-07-19 06:48 UTC, christophenne commented on website/guides/08_package-creation.mdx
> +A current limitation of value definitions is that they can only patch helm values in existing paths, in like the [caddy-ingress-controller](https://medium.com/r/?url=https%3A%2F%2Fgithub.com%2Fcaddys
Please replace the medium link here too.

2024-07-19 06:48 UTC, christophenne commented on website/guides/08_package-creation.mdx
> +The best way to learn is by doing so lets integrate a new package. We have already integrated the ArgoCD operator so let’s add the [Argo workflows](https://medium.com/r/?url=https%3A%2F%2Fargoproj.gi
Please replace the medium link here too.

2024-07-19 09:03 UTC, jakepage91 commented on website/sidebar-guides.ts
> +      items: ['cert-manager', 'ingress-nginx', 'rabbitmq', 'quickwit', 'kube-prom-stack', 'package-creation'],
True, yeah!

2024-07-19 09:08 UTC, christophenne approved these changes

2024-07-19 15:02 UTC, pmig approved these changes

2024-07-19 15:05 UTC, merged