feat(cli): add --dry-run to uninstall command
glasskube/glasskube pull request #1069
Opened 2024-08-05 14:56 UTC by hanshal101

Closes #1061 
Fixes #1061 

## 📑 Description
This PR adds the `DryRun` options to the uninstall command

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-08-05 16:26 UTC, christophenne submitted a review, later dismissed
@hanshal101 please test your implementation again, when running `glasskube uninstall cyclops --dry-run`, the command never finishes or seems to wait forever.

2024-08-12 12:40 UTC, hanshal101 commented
Hey @christophenne sorry for the late update, this error was caused in the `awaitDeletion` function, here I have passed the `isDryRun` bool to check if its true then return nil.

2024-08-13 10:36 UTC, kosmoz requested changes
I think it would be better to keep the logic out of the await function (see suggestions below).

Also, I think there should be some feedback that dry run mode is enabled. See for example the configure command: https://github.com/hanshal101/glasskube/blob/26abda901fab05ceee737a99c710997f48b6c453/cmd/glasskube/cmd/configure.go#L51-L53

2024-08-13 10:36 UTC, kosmoz commented on pkg/uninstall/uninstall.go
> +	return obj.awaitDeletion(ctx, pkg, isDryRun)
```suggestion
	if isDryRun {
		return nil
	} else {
		return obj.awaitDeletion(ctx, pkg)
	}
```

2024-08-13 10:36 UTC, kosmoz commented on pkg/uninstall/uninstall.go
> +
```suggestion
func (obj *uninstaller) awaitDeletion(ctx context.Context, pkg ctrlpkg.Package) error {
```

2024-08-14 10:07 UTC, kosmoz commented
> Also, I think there should be some feedback that dry run mode is enabled. See for example the configure command: https://github.com/hanshal101/glasskube/blob/26abda901fab05ceee737a99c710997f48b6c453/cmd/glasskube/cmd/configure.go#L51-L53

Please add some feedback that dry-run is enabled.

2024-08-14 14:09 UTC, hanshal101 commented
Code updated !!!

2024-08-16 08:32 UTC, kosmoz commented on cmd/glasskube/cmd/uninstall.go
> +
Please move this so that it is shown before the uninstall details and confirmation prompt

2024-08-19 18:46 UTC, kosmoz approved these changes

2024-08-19 18:50 UTC, merged