feat(cli): create namespace if necessary when installing a package
glasskube/glasskube pull request #1131
Opened 2024-08-23 17:00 UTC by hanshal101

Closes #1101 
Fixes #1101

## 📑 Description
This PR fixes the bug Creating namespace if necessary when installing a namespace-scoped Package.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
My `list` got broke after solving this, it looks something like this, need help here:
![image](https://github.com/user-attachments/assets/3a49a453-44eb-4bd3-bf6c-b423731d5651)

2024-08-23 18:00 UTC, kosmoz commented
> My `list` got broke after solving this, it looks something like this, need help here:

What do you mean when you say it's broken? It looks fine to me

2024-08-23 18:02 UTC, hanshal101 commented
Ohh so I think its just with me I guess, I'm sorry my terminal size was small hence was not showing all details

2024-09-03 16:54 UTC, hanshal101 commented
Hey, just making an update in the PR. I'll take a week to solve this !!! sorry for the inconvenience

2024-09-08 09:17 UTC, hanshal101 commented
Just made all the changes here, while I was not clear with adding the `namespace check and install` in the install function.

2024-09-13 15:14 UTC, hanshal101 commented
> need this sooner and I took this over and fixed and the

Cool, Sorry for the delay though

2024-09-16 07:49 UTC, kosmoz requested changes

2024-09-16 07:49 UTC, kosmoz commented on cmd/glasskube/cmd/install.go
> +				fmt.Printf(" * Namespace %v does not exist and will be created\n",
```suggestion
				fmt.Fprintf(os.Stderr, " * Namespace %v does not exist and will be created\n",
```

2024-09-16 07:49 UTC, kosmoz commented on internal/namespaces/ultils.go
> +}
I'm not convinced this function adds much on top of just calling `Create` directly

2024-09-16 07:49 UTC, kosmoz commented on internal/namespaces/ultils.go
> +func IsNamespaceInstalled(ctx context.Context, cs *kubernetes.Clientset, namespace string) (bool, error) {
Personally, I would change the name to simply `Exists`, since
1. A namespace is not installed and
2. the package is already called namespaces

2024-09-16 09:36 UTC, kosmoz approved these changes

2024-09-16 09:39 UTC, merged