docs(website): initial helm guide article
glasskube/glasskube pull request #1302
Opened 2024-10-03 17:08 UTC by jakepage91

Closes # 

## 📑 Description

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-10-03 17:09 UTC, jakepage91 commented
![Dev to thumbnails (27)](https://github.com/user-attachments/assets/c9d25d02-d536-471c-be89-54ed3fd7a909)
![Dev to thumbnails (26)](https://github.com/user-attachments/assets/dd0c743a-684d-476d-a904-34c10cef48c3)

2024-10-03 19:49 UTC, jakepage91 commented
![Dev to thumbnails (28)](https://github.com/user-attachments/assets/6ad23c50-ca8b-45f2-93ff-83bbaa9f8749)
![Dev to thumbnails (29)](https://github.com/user-attachments/assets/0e7393c0-7707-4081-b81e-19278cfcb39e)

2024-10-08 18:01 UTC, pmig requested changes
Looks good, I would suggest also linking to our 5 shortcomings of helm article. Either in the dependency management warning section as "this is one of the shortcomings we explained on our other article about helm" or in the conclusion. Or maybe even both.

Maybe we can also add some more internal links. E.g. validating yaml files we can link to the complete kubectl guide :-)

2024-10-08 19:02 UTC, jakepage91 commented
> Looks good, I would suggest also linking to our 5 shortcomings of helm article. Either in the dependency management warning section as "this is one of the shortcomings we explained on our other article about helm" or in the conclusion. Or maybe even both.
> 
> Maybe we can also add some more internal links. E.g. validating yaml files we can link to the complete kubectl guide :-)

Done!

2024-10-08 19:55 UTC, pmig requested changes
Last small request:

I suggest alway`/blog/5-helm...` instead of `https://glasskube.dev/blog..` this ensures a easier top level domain switch and for local dev links don't break out ot a sudden :-)

2024-10-08 19:56 UTC, pmig commented on website/blog/2024-10-03-helm-guide/index.mdx
> +**Remote Repositories:** These are online , mostly on GitHub, that host publicly available Helm charts. You can also find charts on GitLab, BitBucket, and other code hosting platforms too. For privat
also here

2024-10-08 20:36 UTC, jakepage91 commented on website/blog/2024-10-03-helm-guide/index.mdx
> +**Remote Repositories:** These are online , mostly on GitHub, that host publicly available Helm charts. You can also find charts on GitLab, BitBucket, and other code hosting platforms too. For privat
Done!

2024-10-11 15:45 UTC, thekubernaut approved these changes

2024-10-11 15:48 UTC, merged