docs(webiste): improve comparision documentation
glasskube/glasskube pull request #246
Opened 2024-02-12 14:03 UTC by pmig

## 📑 Description
As we still get a lot of feedback about the differences to other solutions I improved the comparison section on our website.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

2024-02-12 14:21 UTC, pmig commented on website/docs/04_comparisons/01_helm.md
> +5. **Kubernetes version upgrade compatibility**<br/>Glasskube tires to make Kubernetes version upgrades as smooth as possible by automatically testing all package (combinations) across multiple Kuber
This section is new

2024-02-12 14:23 UTC, pmig commented on website/docs/04_comparisons/01_helm.md
> +description: Discover Glasskube, a fresh Kubernetes package manager challenging Helm's shortcomings. Explore automatic updates, dependency management and much more.
The description and the ordered list (second comment) is new the other paragraphs did not change (much), but due to the new file name GitHub doesn't show a meaningful side-by-side view.

2024-02-12 14:27 UTC, christophenne requested changes

2024-02-12 14:27 UTC, christophenne commented on website/docs/04_comparisons/01_helm.md
> +4. **Cloud-Native architecture**<br/>As helm's architecture is purely client side, as it renders our the templates and apply them via the Kubernetes API. Although releases are stored in Kubernetes Se
The first sentence looks a bit off - two times "as" and "our the templates"

2024-02-12 14:27 UTC, christophenne commented on website/docs/04_comparisons/01_helm.md
> +4. **Cloud-Native architecture**<br/>As helm's architecture is purely client side, as it renders our the templates and apply them via the Kubernetes API. Although releases are stored in Kubernetes Se
Second sentence: "making *it* harder..." ?

2024-02-12 14:27 UTC, christophenne commented on website/docs/04_comparisons/01_helm.md
> +5. **Kubernetes version upgrade compatibility**<br/>Glasskube tires to make Kubernetes version upgrades as smooth as possible by automatically testing all package (combinations) across multiple Kuber
Glasskube *tries*

2024-02-12 14:27 UTC, christophenne commented on website/docs/04_comparisons/02_timoni.md
> +Timoni is closer related to helm than Glasskube, but brings some features and new approaches to the table Helm doesn't offer.
helm should be uppercase

2024-02-12 14:35 UTC, kosmoz requested changes

2024-02-12 14:35 UTC, kosmoz commented on website/docs/04_comparisons/02_timoni.md
> +Timoni is in general already more mature than Glasskube, but doesn't focus on providing an easy way of package installation and upgrades and as of now there is also no GUI support planned
I think this sentence is too long and has too many "and"s. I think it should be split into two sentences.

2024-02-12 14:35 UTC, kosmoz commented on website/docs/04_comparisons/01_helm.md
> +3. **Custom Resources Definition (CRD) changes**<br/>Upgrading CRDs will be taken care of by Glasskube to ensure CRs and it's operators don't get out-of-sync. These updates are performed via server-s
it's -> its

Additionally, I'm not sure if SSA really adds any benefit here

2024-02-12 14:35 UTC, kosmoz commented on website/docs/04_comparisons/01_helm.md
> +We are trying to take new approach on multiple features, but want to highlight the 5 most important differences that got either just released, are in development right now or are on our roadmap and w
I think it sounds better like this: 

```suggestion
We take new approach on multiple features, but want to highlight the 5 most important differences that got either just released, are in development right now or are on our roadmap and will be started soon:
```

2024-02-12 14:35 UTC, kosmoz commented on website/docs/04_comparisons/01_helm.md
> +2. **Dependency management**<br/>Glasskube offers - as you would expect - dependency management out of the box. Multiple packages can require a specific package (e.g. `cert-manager`) being installed
[emdash](https://www.thesaurus.com/e/grammar/em-dash/)

2024-02-13 06:40 UTC, christophenne approved these changes

2024-02-13 06:40 UTC, christophenne commented on website/docs/04_comparisons/01_helm.md
> +4. **Cloud-Native architecture**<br/>As Helm's architecture is purely client side, it renders the templates and apply them via the Kubernetes API. Although releases are stored in Kubernetes Secrets t
apply -> applies

2024-02-13 09:37 UTC, pmig commented on website/docs/04_comparisons/01_helm.md
> +4. **Cloud-Native architecture**<br/>As Helm's architecture is purely client side, it renders the templates and apply them via the Kubernetes API. Although releases are stored in Kubernetes Secrets t
thanks, fixed! :-)

2024-02-13 10:40 UTC, kosmoz requested changes

2024-02-13 10:40 UTC, kosmoz commented on website/docs/04_comparisons/01_helm.md
> +We take new approach on multiple features, but want to highlight the 5 most important differences that got either just released, are in development right now or are on our roadmap and will be started
```suggestion
We take a new approach on multiple features, but want to highlight the 5 most important differences that got either just released, are in development right now or are on our roadmap and will be started soon:
```

2024-02-13 10:45 UTC, kosmoz approved these changes

2024-02-13 10:45 UTC, merged