feat(ui): add dark mode
glasskube/glasskube pull request #313
Opened 2024-02-28 16:03 UTC by kosmoz

## 📑 Description
Let's go dark :sunglasses: 

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-02-29 07:48 UTC, christophenne approved these changes
Looks and works great!

The only thing I'm not so sure about is how the modals look in dark mode. I think it's difficult to grasp that the modal is "on top" of the page – or at least it's easier to see in light mode that something is on top.

2024-02-29 09:41 UTC, kosmoz commented
> Looks and works great!
> 
> The only thing I'm not so sure about is how the modals look in dark mode. I think it's difficult to grasp that the modal is "on top" of the page – or at least it's easier to see in light mode that something is on top.

This is true. I will update the theme and re-import it.

2024-02-29 16:59 UTC, christophenne requested changes
Nice changes :rocket: 

The only other comment I have, is that a short section in the CONTRIBUTING.md would be nice: how to set up for web development or something like that – since now one needs to run `npm i`.

2024-02-29 16:59 UTC, christophenne commented on Makefile
> +build-cli: fmt vet lint lint-web web ## Build cli binary.
I think the `lint` target should now be called `lint-go`, or if it stays `lint`, it should also execute `lint-web`. But in the latter the `lint-fix` would also need to include a new target `lint-fix-web` (which itself would probably execute `prettier:write`?).

2024-03-01 08:00 UTC, christophenne approved these changes

2024-03-01 08:06 UTC, merged