feat(cli): show entrypoints in glasskube describe command
glasskube/glasskube pull request #346
Opened 2024-03-11 15:28 UTC by hanshal101

Closes #297 
Fixes #297 

## 📑 Description
Added entrypoints in the `glasskube desscribe` command

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-03-12 10:41 UTC, christophenne requested changes
Hi, thanks for your PR. I have some comments on the implementation, so please have a look at it. 

When you are done, please also squash your commits and force-push on your branch – That way the PR and later on, our commit history, will only contain one commit.

2024-03-12 10:41 UTC, christophenne commented on pkg/describe/describe.go
> +) (*v1alpha1.Package, *client.PackageStatus, *v1alpha1.PackageManifest, *[]v1alpha1.PackageEntrypoint, error) {
You don't need to return the array additionally, it is already contained in the returned `PackageManifest`. So there should be no changes necessary to this function.

2024-03-12 10:41 UTC, christophenne commented on cmd/glasskube/cmd/describe.go
> +		if len(*entrypoints) == 0 {
instead of `entrypoints` you can use `manifest.Entrypoints`

2024-03-12 10:41 UTC, christophenne commented on cmd/glasskube/cmd/describe.go
> +					fmt.Fprintf(os.Stderr, "Scheme: %s\n", i.Scheme)
if `Scheme == ""`, the output will not contain the linebreak at the end. And also the colon would be the last sign of an entrypoint. 

I would suggest to use the `strings.Join` function here. Inside the loop you can hold an array `messageParts []string`, and for each property you can do `messageParts = append(messageParts, fmt.Sprintf("<property-name>: %s", <property-value>))` and at the end of the loop you call the join function on these message parts with the "," as delimiter.

2024-03-13 13:44 UTC, kosmoz approved these changes

2024-03-13 13:45 UTC, christophenne approved these changes

2024-03-13 13:46 UTC, merged