feat: add version mismatch detection for PackageOperator
glasskube/glasskube pull request #373
Opened 2024-03-14 13:01 UTC by Baalekshan

Closes # 

## 📑 Description

This PR adds a feature to detect version mismatch between PackageOperator & CLI and notifies the user.
  
**Changes Made:**
Moved GetPackageOperatorVersion() to `glasskube/internal/cliutils/versionutil.go`
added CheckPackageOperatorVersion() function

```
 $ ./glasskube list
❗ Glasskube PackageOperator needs to be updated: 0.0.4 -> dev
💡 Please run `glasskube bootstrap` again to update Glasskube PackageOperator
NAME                  STATUS         VERSION
argo-cd               Not installed    
cert-manager          Not installed    
cyclops               Not installed    
ingress-nginx         Not installed    
keptn                 Not installed    
kubernetes-dashboard  Not installed    
```
```
$ ./glasskube version
❗ Glasskube PackageOperator needs to be updated: 0.0.4 -> dev
💡 Please run `glasskube bootstrap` again to update Glasskube PackageOperator
glasskube: vdev
package-operator: v0.0.4
```

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-03-18 13:49 UTC, kosmoz requested changes
Generally, I like this implementation. It's very clean!

However, I think it should be possible to toggle this behavior when calling the `SetupClientContext` function, similar to `requireBootstraped`. This way, we could re-use the already existing `--skip-version-check` flag (which is true by default in dev builds) and skip the check completely for the bootstrap command, since I think it doesn't really make any sense there.

Do you think you could incorporate this change @Baalekshan?

2024-03-18 14:05 UTC, Baalekshan commented
I will try @kosmoz

2024-03-19 13:21 UTC, Baalekshan commented
@kosmoz I could continue working on this once pr #395 is merged.

2024-03-20 12:09 UTC, Baalekshan commented
@kosmoz , changes has been done :)

2024-03-20 12:53 UTC, kosmoz approved these changes

2024-03-20 12:54 UTC, merged