docs: describe dependencies and changes to package repo (#316)
glasskube/glasskube pull request #392
Opened 2024-03-18 16:21 UTC by christophenne

Closes #316

## 📑 Description

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-03-20 08:18 UTC, christophenne commented on website/docs/03_components/03_package-repository.md
> +### Version Numbers
@pmig @kosmoz please have a look at this in particular – that's how I interpreted what we decided back then.

2024-03-20 09:11 UTC, pmig requested changes

2024-03-20 09:11 UTC, pmig commented on website/docs/03_components/03_package-repository.md
> +If the package manifest turns out to be faulty and need to be corrected (e.g. typos, wrong entrypoints), the maintainer needs to add a version `2.7.0+2`.
I would limit the increase of the build number to "errors". We might also increase it for metadata updates, dependency changes or any other update to the package it self that does not change the app versions

2024-03-20 11:03 UTC, kosmoz approved these changes

2024-03-21 09:39 UTC, pmig approved these changes

2024-03-21 09:44 UTC, merged