docs(website): new Discord blog post + updated pic for v0.1.0 blog
glasskube/glasskube pull request #435
Opened 2024-03-26 12:23 UTC by jakepage91

## 📑 Description
Publishing new blog post and also updating a screenshot in the previous v0.1.0 release blog

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
I'm still coming up as unverified and will probably need help to find out how to fix it.

2024-03-26 12:34 UTC, pmig requested changes

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +Configuring a **top-tier server** is not difficult at all, the [Glasskube server](discord.gg/SxH6KUCGH7) is an example of a **“less is more”** approach. Having said that, we will explore some additio
```suggestion
Configuring a **top-tier server** is not difficult at all, the [Glasskube server](https://discord.gg/SxH6KUCGH7) is an example of a **“less is more”** approach. Having said that, we will explore some additional intermediate and advanced practices that might make sense for some use cases. Let’s not waste any more time and jump straight in. 
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 1- Don't Reinvent the Wheel 🛞
```suggestion
## 1. Don't Reinvent the Wheel 🛞
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 2- Establish Clear Lines of Communication 🗣️
```suggestion
## 2. Establish Clear Lines of Communication 🗣️
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 3- Are you Into Role-Play? 📛
```suggestion
## 3. Are you Into Role-Play? 📛
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 4- Enable the Community Feature ✅
```suggestion
## 4. Enable the Community Feature ✅
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 5- Have a Short but Effective Onboarding Process 👋
```suggestion
## 5. Have a Short but Effective Onboarding Process 👋
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 6- Structured Help and Support Forums 🆘
```suggestion
## 6. Structured Help and Support Forums 🆘
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 7 - Keep the Announcements Coming 🎉
```suggestion
## 7. Keep the Announcements Coming 🎉
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 8 - How to Avoid Raiding, Spam, and Nukes ⚠️
```suggestion
## 8. How to Avoid Raiding, Spam, and Nukes ⚠️
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +## 9 - Adding Fun with Emojis and Stickers 🤣
```suggestion
## 9. Adding Fun with Emojis and Stickers 🤣
```

2024-03-26 12:34 UTC, pmig commented on website/blog/2024-03-26-discord-setup/index.mdx
> +A community is made up of individual connections to try to focus more on initiatives that will lead to open conversation and always try to acknowledge key community members when they deserve it.
I would recommend a call to action section similar to the release blog post (but slightly adapted):

## Get involved

The easiest way to get involved is to tackle one of our [open issues](https://github.com/glasskube/glasskube/issues).
You are also welcome to join our [Discord](https://discord.gg/SxH6KUCGH7).

> **If you are a cloud native developer, please [submit your package](https://github.com/glasskube/glasskube/discussions/90)**.

As Glasskube is still in its very early days, your feedback is highly appreciated.
Let us know what you think, we would love to hear from you or support us by leaving a star on GitHub:

[⭐ `glasskube/glasskube` ⭐](https://github.com/glasskube/glasskube/)

2024-03-26 12:36 UTC, pmig requested changes
The blog post is really well written and super interesting. I just discovered a broken link, suggest another enumeration suffix and a missing CTA for a GitHub star or something like "Join our Discord to see it action". We can than create a Discord bot that  reminders new joiners to checkout the glasskube repo and star it :-)

2024-03-26 14:28 UTC, pmig approved these changes

2024-03-26 14:28 UTC, merged

2024-09-04 18:55 UTC, jakepage91 commented
![Dev to thumbnails (14)](https://github.com/user-attachments/assets/3d4d0bee-fa39-4d52-8873-09d9226c1b18)

![ray-so-export (1)](https://github.com/user-attachments/assets/3dab678a-1ff7-4167-82b6-975070c70a0d)
![Screenshot 2024-08-16 at 17 36 41](https://github.com/user-attachments/assets/afc36885-6781-4cda-b8e7-7e1de59902ef)
<img width="1161" alt="Screenshot 2024-09-03 at 04 53 53" src="https://github.com/user-attachments/assets/b9773cf0-03bf-4fa4-9dbd-b2bf2a887e38">
<img width="1474" alt="Screenshot 2024-09-03 at 17 37 59" src="https://github.com/user-attachments/assets/c0ba2ec4-569d-4f66-bcde-b77944fef629">
![Screenshot 2024-08-16 at 17 44 47](https://github.com/user-attachments/assets/74dd15b1-ebdc-4071-b02e-00d802e8a71b)
![Screenshot 2024-08-16 at 17 32 22](https://github.com/user-attachments/assets/96b267f7-e82d-4539-9d67-2468bd2ba636)
![Screenshot 2024-08-23 at 18 14 29](https://github.com/user-attachments/assets/491b146a-63a0-4585-93ee-aac8b7013f53)
![Area](https://github.com/user-attachments/assets/99f7a638-718d-4ca7-8242-d25fbd91528c)
![Launch week - twitter-post (7)](https://github.com/user-attachments/assets/236af5f2-64a9-42f2-92f8-a30438777365)