feat(ui): reuse transaction when applying updates (#295)
glasskube/glasskube pull request #438
Opened 2024-03-26 16:25 UTC by christophenne

Closes #295

## 📑 Description

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-03-27 11:20 UTC, kosmoz requested changes
Here are some comments about the implementation.

More generally, I feel like this is not really reusing the existing transaction but validating that nothing has changed in the time between showing the dialog and confirming the update. Related to that, I would have expected that the old transaction to still be applied in case something has changed in the meantime (of course the "update available" banner would still be visible).

With that said, I still think this is a good thing to have but I would keep the issue open for now.

2024-03-27 13:30 UTC, christophenne commented on internal/web/templates/components/pkg-update-modal.html
> +      <form hx-post="/packages/update?{{ .UpdateTransactionParams }}">
I dislike both, and both seem non-idiomatic to me :smiley: I can change it though.

2024-03-27 15:03 UTC, kosmoz commented on internal/web/templates/components/pkg-update-modal.html
> +      <form hx-post="/packages/update?{{ .UpdateTransactionParams }}">
I think this is exactly what `<input type="hidden">` is for though :thinking:

2024-03-27 15:19 UTC, kosmoz commented
> True, it's a validation. It's pragmatic but I doubted that reusing the old transaction is worth the implementation effort of either holding something server-side or changing the updater to support version-specific updates for multiple packages. That's the two approaches I saw, but I decided against them because I thought this validation is probably good enough – it's not like this is going to happen too often. I don't know to be honest, it's all not that great.
> 
> But if we decide that we want to do the transaction-reuse thing, I would do it right away instead of this validation.

Couldn't we just store a `map[int]update.Transaction` or something like that in the `server` and let the update modal form tell us the key of the transaction it should apply after confirmation (using an `<input type="hidden">` :smile:)? For the key we can use `rand.Int()`.

2024-03-28 11:09 UTC, christophenne commented
> > True, it's a validation. It's pragmatic but I doubted that reusing the old transaction is worth the implementation effort of either holding something server-side or changing the updater to support version-specific updates for multiple packages. That's the two approaches I saw, but I decided against them because I thought this validation is probably good enough – it's not like this is going to happen too often. I don't know to be honest, it's all not that great.
> > But if we decide that we want to do the transaction-reuse thing, I would do it right away instead of this validation.
> 
> Couldn't we just store a `map[int]update.Transaction` or something like that in the `server` and let the update modal form tell us the key of the transaction it should apply after confirmation (using an `<input type="hidden">` 😄)? For the key we can use `rand.Int()`.

Fair enough, changed it.

2024-03-28 13:27 UTC, kosmoz approved these changes
Looks good!

2024-03-28 14:17 UTC, merged