--output support for glasskube update
glasskube/glasskube pull request #669
Opened 2024-05-21 17:56 UTC by Aryakoste

Closes #657 

## 📑 Description

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-05-22 08:38 UTC, kosmoz reviewed
I would put this on hold until https://github.com/glasskube/glasskube/pull/670#pullrequestreview-2070528628 is resolved.

2024-05-24 08:50 UTC, kosmoz requested changes
Hey @Aryakoste! Since your other PR just got merged, could you please update this one to use the new `OutputOptions`?

2024-05-25 09:54 UTC, Aryakoste commented
Done @kosmoz

2024-05-27 08:51 UTC, kosmoz requested changes
As noted in the issue description, the output of the command should be the list of serialized `Package` resources after being updated, not the update transaction. 

To achieve this, you will probably have to modify the `updater.Apply` function to return that data. If the output is YAML, the list should be printed as multi-document YAML, similar to what we already do in the `ListCommand`.

2024-05-28 18:17 UTC, Aryakoste commented
Changes done check and let me know @kosmoz

2024-05-29 11:51 UTC, kosmoz requested changes
Looks good now. Please have a look at this final comment, afterwards I think this is ready to merge!

2024-05-29 11:51 UTC, kosmoz commented on cmd/glasskube/cmd/update.go
> +			buffer.Write([]byte("---\n"))
This leads to an empty document at the end. Please print the document separator before the content and only if there are two or more packages.

2024-06-03 17:27 UTC, Aryakoste commented
@kosmoz Changes done.

2024-06-04 09:54 UTC, kosmoz requested changes
Looks great but can you please ensure that all packages have the correct `TypeMeta`? With that addressed, I think this would be ready for merge.

You can check out https://github.com/Aryakoste/glasskube/blob/7b9ce5ba8346c3ad20c8e4b10d3e066f2dcbef26/cmd/glasskube/cmd/configure.go#L90-L92 as a reference

2024-06-06 09:34 UTC, kosmoz approved these changes

2024-06-06 09:46 UTC, merged