feat(cli): add json and yaml output to the describe command
glasskube/glasskube pull request #673
Opened 2024-05-22 05:17 UTC by hanshal101

Closes #655 
Fixes #655 

## 📑 Description
This PR adds the feature of getting the output in the `JSON` and `YAML` formats.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
I have made changes in the `list.go` to0, here the JSON and YAM was defined as `ListFormat` which will return an error if used somewhere else. Hence I declared them to string and called them as `ListFormat(JSON)`

2024-05-24 09:00 UTC, kosmoz requested changes
Hey @hanshal101! Here is some feedback regarding your PR. Sorry for taking a while to address this.

1. We just merged another PR that streamlines the process of adding the output flag to a command. You can check it out here: https://github.com/glasskube/glasskube/pull/670. Please update this PR to use the new `OutputOptions`.
2. I don't think it's necessary to create a new struct for the structured output. Printing just the package should be fine.
3. We recently merged a big feature (https://github.com/glasskube/glasskube/pull/618) which caused some merge conflicts with your branch. Can you please rebase (or re-create) your branch to resolve these conflicts?

As always, let us know if you have any questions or require assistence!

2024-05-29 12:17 UTC, hanshal101 commented
Hey @kosmoz , I have made a another PR for this as I received some conflict issues during rebase. 
Continues #717

2024-05-29 12:21 UTC, kosmoz commented
> Hey @kosmoz , I have made a another PR for this as I received some conflict issues during rebase. Continues #717

OK, should we close this one?

2024-05-29 12:23 UTC, hanshal101 commented
Yup

2024-05-29 12:23 UTC, closed without merging