Recent blogs in home page of website
glasskube/glasskube pull request #874
Opened 2024-06-25 19:28 UTC by Aryakoste

Closes #800 

## 📑 Description

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-06-26 13:18 UTC, kosmoz requested changes
I think this looks really good for a start. Please check my comments below regarding the styling.

Additionally, the build seems to be failing because home.tsx is interpreted to be a page because it is in the pages directory. You can fix that my moving home.tsx and index.module.css to /src/components/home/ and fixing the reference in the custom blog plugin.

Lastly, please make sure to format your newly created files using `npx prettier -w src/components/HomepageBlogs/*`.

2024-06-26 13:18 UTC, kosmoz commented on website/src/components/HomepageBlogs/index.tsx
> +                  <p>{post.metadata.description}</p>
```suggestion
                  <div>{post.metadata.description}</div>
```

2024-06-26 16:49 UTC, Aryakoste commented
@kosmoz Changes done.

2024-06-27 09:38 UTC, kosmoz approved these changes

2024-06-28 10:07 UTC, pmig requested changes
Thanks for you contribution I merged another pull request removing the the ASCII video. Could you fix the merge conflicts?

I also requests some smaller (wording) changes.

2024-06-28 10:07 UTC, pmig commented on website/src/components/HomepageBlogs/index.tsx
> +              <Link to={useBaseUrl('/blog')}>Check it out!</Link>
```suggestion
              We are regularly writing <Link to={useBaseUrl('/blog')}>blog posts</Link> and publish <Link to={useBaseUrl('//guides/categories/')}>guides</Link>. Find our latest blog posts below.
              
```

2024-06-28 16:12 UTC, Aryakoste commented
@pmig @kosmoz Changes done.

2024-07-04 06:20 UTC, pmig approved these changes

2024-07-04 06:23 UTC, merged