docs: exchange AsciinemaPlayer with youtube demo video embed (#873)
glasskube/glasskube pull request #883
Opened 2024-06-26 13:41 UTC by MridulDhiman

Closes #873 

## 📑 Description
Removes the deprecated AsciinemaPlayer, and replaces with embed of youtube demo video present in README.md file.

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information
1. Uninstalled `asciinema-player@3.8.0` package from the `package.json`.
2. Deleted `AsciimaPlayer` components from the components directory.

2024-06-26 13:44 UTC, pmig requested changes
Thanks we should use the https://www.youtube-nocookie.com domain

2024-06-26 13:44 UTC, pmig commented on website/src/pages/index.tsx
> +            <iframe width="100%" height="460" src="https://www.youtube.com/embed/aIeTHGWsG2c?si=KUcqvY4coU89GmdK" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboar
```suggestion
            <iframe width="100%" height="460" src="https://www.youtube-nocookie.com/embed/aIeTHGWsG2c?si=KUcqvY4coU89GmdK" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
```

2024-06-27 09:49 UTC, kosmoz requested changes

2024-06-27 09:49 UTC, kosmoz commented on website/src/pages/index.tsx
>                Learn how to install cert-manager in less than 2 minutes using Glasskube
```suggestion
              Learn how to use Glasskube in less than 2 minutes
```

2024-06-27 09:52 UTC, kosmoz approved these changes

2024-06-27 09:55 UTC, kosmoz approved these changes

2024-06-28 09:09 UTC, pmig approved these changes

2024-06-28 09:11 UTC, merged