docs(website): quickwit assets
glasskube/glasskube pull request #936
Opened 2024-07-02 13:40 UTC by jakepage91

## 📑 Description
Added the Quickwit blog and guide

## ✅ Checks
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required

## ℹ Additional Information

2024-07-04 06:22 UTC, pmig requested changes

2024-07-04 06:22 UTC, pmig commented on website/blog/2024-07-02-quickwit/index.mdx
> +tags: [ glasskube ]
With the introduction of https://github.com/glasskube/glasskube/pull/874 all blog posts now need an image attribute as a preview image for the front page

2024-07-04 06:23 UTC, pmig commented
@kosmoz as I am about to board my flight could you take over this pr and approve it, once @jakepage91 implemented the changes?

2024-07-05 08:47 UTC, kosmoz approved these changes

2024-07-05 08:51 UTC, merged